ci:
    skip: [
      # The pre-commit.ci runner has an outdated python version
      poetry-lock
    ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.0b3'
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
      - id: pyupgrade
        exclude: "^notebooks/"
        args: ["--py3-plus", "--py310-plus"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    # https://github.com/psf/black/blob/main/docs/guides/using_black_with_other_tools.md
    hooks:
      - id: isort
        args: ["--profile=black"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
        args:
          [
            "--target-version",
            "py310",
          ]
