ci:
  skip: [
      # The pre-commit.ci runner has an outdated python version
      poetry-lock,
      # There is no network access at pre-commit.ci
      check-jsonschema,
    ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: "2.2.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        exclude: "^notebooks/"
        args: ["--py3-plus", "--py310-plus"]
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    # https://github.com/psf/black/blob/main/docs/guides/using_black_with_other_tools.md
    hooks:
      - id: isort
        args: ["--profile=black"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3
        args: ["--target-version", "py310"]
  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.1
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-jsonschema
        name: Validate pyproject.toml
        args: ["--schemafile", "https://json.schemastore.org/pyproject.json"]
        files: ^pyproject.*
        types_or: [toml]
