[tool.poetry]
authors = []
description = ""
license = "MIT OR Apache-2.0"
name = "python-snippets"
version = "0.1.0"
repository = "https://github.com/jonasbb/python-snippets"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
mypy = "^0.961"
pytest = "^7.1.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
