name: Test and Typecheck the project

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: read-all

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install poetry"
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry install
      - run: poetry run pytest --markdown-docs

  typechecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install poetry"
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry install
      - run: poetry run mypy python_snippets
